// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ycAodvvkQYUuO95cKAnKC70II1tGnw0',
    appId: '1:785916255104:android:87a9c8db58ce2ae8537f65',
    messagingSenderId: '785916255104',
    projectId: 'book-discovery-c7f4a',
    databaseURL: 'https://book-discovery-c7f4a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-discovery-c7f4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1AaVKxAHScVogAKlOq2NoDO2NvT2Js2k',
    appId: '1:785916255104:ios:de07bcfad9d068d3537f65',
    messagingSenderId: '785916255104',
    projectId: 'book-discovery-c7f4a',
    databaseURL: 'https://book-discovery-c7f4a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-discovery-c7f4a.firebasestorage.app',
    androidClientId: '785916255104-jc08uj7ls1mde8oj1hmk8og43rt2sjfh.apps.googleusercontent.com',
    iosClientId: '785916255104-mkn95aj04ar5t0n5ver28u9mt5uh6jij.apps.googleusercontent.com',
    iosBundleId: 'com.ayush.bookDiscovery',
  );

}